import AOSProvider from "@/components/AOSProvider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { AuthProvider } from "@/contexts/AuthContext";
import { CartProvider } from "@/contexts/CartContext";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Poppins, Syne } from "next/font/google";
import "toastify-js/src/toastify.css";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

const syne = Syne({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-syne",
});

export const metadata: Metadata = {
  title: "Empire Sports",
  //   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`min-h-screen ${poppins.variable} ${syne.variable}`}>
        <AuthProvider>
          <CartProvider>
            <AOSProvider>
              <Header />
              {children}
              <Footer />
            </AOSProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
